version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "80:8000" # Expose Laravel on live server port 80
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://yourdomain.com

      DB_CONNECTION: mysql
      DB_HOST: your-northflank-db-host
      DB_PORT: 3306
      DB_DATABASE: your-db
      DB_USERNAME: your-user
      DB_PASSWORD: your-pass

    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: strongrootpass
      MYSQL_DATABASE: your-db
      MYSQL_USER: your-user
      MYSQL_PASSWORD: your-pass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
